spring.application.name=job-engine
server.port=${PORT:5432}

# Database configuration for Render's Postgres
spring.datasource.url=jdbc:postgresql://dpg-d6ebs5stgctc73dvmjrg-a.oregon-postgres.render.com/jbdb_eoqm
spring.datasource.username=anna
spring.datasource.password=CeqHrJEjDUZSS2YqmiduRXYA4Q1pc9ck
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true